name: Task
description: 기본 업무 템플릿
title: "[Task] "
labels: []
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: 작업 내용
      description: 무엇을 해야 하나요?
      placeholder: 예) EDA, 데이터 전처리
    validations:
      required: true
